# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_gb_location <- function(gb_base_span) {
    .Call('biofiles_parse_gb_location', PACKAGE = 'biofiles', gb_base_span)
}

get_qual <- function(lines) {
    .Call('biofiles_get_qual', PACKAGE = 'biofiles', lines)
}

parse_feature_table <- function(id = 0L, lines = character(""), seqinfo) {
    .Call('biofiles_parse_feature_table', PACKAGE = 'biofiles', id, lines, seqinfo)
}

