# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @internal
gbFeature <- function(feature, seqenv, id = 0L) {
    .Call('biofiles_gbFeature', PACKAGE = 'biofiles', feature, seqenv, id)
}

gbLocation <- function(gb_base_span, accession = "") {
    .Call('biofiles_gbLocation', PACKAGE = 'biofiles', gb_base_span, accession)
}

